### ISSUE TITLE
Cart: add item (possible from product list or product detail pages)

### ISSUE THREAD

**Issue by emshuttles** [grace-shopper-super-team/woodshop#38]

**Comment by knoebelja** [comment]
CartList component to load cart state
CartItem components to display each item in the cart
ItemQuantity to display CartItem quantity and modify

This should be persistent.

**Comment by onggunhao** [comment]
Cart Icon now shows up in Navbar ref commit hash 112fabf0e7

**Comment by onggunhao** [comment]
Todo: Make Cart Icon show the number of items in the cart
