### ISSUE TITLE
Cart: can login and keep cart

### ISSUE THREAD

**Issue by emshuttles** [grace-shopper-super-team/woodshop#42]

**Comment by onggunhao** [comment]
Breaking it down into steps:
1. Make Cart icon show up in the app bar
2. Make Cart modal slide in when Cart icon is clicked. When user clicks outside the modal, the cart disappears
3. Should have state storing the contents of the Cart
4. Each product should have an "Add to Cart" button
5. When "Add to Cart" is clicked, product should be added to the Cart
