### ISSUE TITLE
Products: search functionality

### ISSUE THREAD

**Issue by emshuttles** [grace-shopper-super-team/woodshop#57]

**Comment by onggunhao** [comment]
There is a good article on how to make a custom App Bar. See https://github.com/callemall/material-ui/issues/5478

**Comment by onggunhao** [comment]
https://stackoverflow.com/questions/40026643/how-to-make-an-app-bar-using-react-material-ui-like-this

**Comment by onggunhao** [comment]
https://stackoverflow.com/questions/40495608/is-it-possible-to-set-up-material-ui-appbar-toolbar-to-have-a-horizontal-tab-men
